### ISSUE TITLE
面试官问我什么是JMM--内存屏障问题？

### ISSUE THREAD

**Issue by hongkunxu** [yehongzhi/learningSummary#1]
感谢博主的总结各篇有营养的文章，下面说一下自己的疑惑问题。
在《面试官问我什么是JMM》中提到了内存屏障，然后给了两个示例，我觉得是有问题的。说一下个人的理解：
1. 一个volatile读，应该是在该指令前加入StoreLoad屏障，在后面加入LoadStore屏障，保障前后的写操作不会对当前命令造成影响，而文中给的例子没有提及在前面加入StoreLoad，反而在后面加入了LoadLoad屏障，我认为读读操作交换顺序是不会产生问题的。
2. 一个volatile写，应该是在该指令前加入LoadStore屏障和StoreStore屏障，在后面加入StoreStore和StoreLoad屏障，如此保证前后的读写操作不会与当前的写操作产生影响。

**Comment by Randomyyds** [comment]
自己去查下资料吧，作者是对的
